// 🔥 REPLACE THIS WITH YOUR RAILWAY URL!!!!
const BACKEND_URL = 'https://YOUR-RAILWAY-URL-HERE.up.railway.app';

// Connect to backend
const socket = io(BACKEND_URL, {
    transports: ['websocket', 'polling'],
    reconnection: true,
    reconnectionDelay: 1000,
    reconnectionAttempts: 10
});

const consoleContent = document.getElementById('console-content');
const statusBadge = document.getElementById('status-indicator');
let usageCount = parseInt(localStorage.getItem('mineHostUsage')) || 0;
const UNLOCK_THRESHOLD = 5;

updateUI();

// Connection handlers
socket.on('connect', () => {
    console.log('✅ Connected to backend!');
    statusBadge.textContent = 'ONLINE';
    statusBadge.className = 'status online';
    clearConsole();
    addLog('> ✅ Connected to MineHost backend', 'success');
    addLog('> 🔥 System ready fr fr', 'success');
    addLog('> 💻 Click "Start Server" to begin', 'info');
});

socket.on('disconnect', () => {
    console.log('❌ Disconnected from backend');
    statusBadge.textContent = 'OFFLINE';
    statusBadge.className = 'status error';
    addLog('> ⚠️ Connection lost to backend', 'error');
});

socket.on('connect_error', (error) => {
    console.error('Connection error:', error);
    statusBadge.textContent = 'CONNECTION ERROR';
    statusBadge.className = 'status error';
    addLog('> ❌ Failed to connect to backend', 'error');
    addLog('> Check if Railway backend is running', 'error');
});

socket.on('reconnect', (attemptNumber) => {
    addLog(`> 🔄 Reconnected after ${attemptNumber} attempts`, 'success');
});

// Server logs
socket.on('console-log', (msg) => {
    addLog(msg.trim());
});

function clearConsole() {
    consoleContent.innerHTML = '';
}

function addLog(message, type = 'normal') {
    const line = document.createElement('div');
    line.textContent = message;
    
    if (type === 'error') {
        line.style.color = '#ff5252';
    } else if (type === 'success') {
        line.style.color = '#4caf50';
    } else if (type === 'info') {
        line.style.color = '#42a5f5';
    } else if (type === 'warning') {
        line.style.color = '#ffa726';
    }
    
    consoleContent.appendChild(line);
    consoleContent.scrollTop = consoleContent.scrollHeight;
}

function startServer() {
    if (!socket.connected) {
        addLog('> ❌ Not connected to backend! Reconnecting...', 'error');
        socket.connect();
        return;
    }
    
    addLog('> 📡 Sending start command to Railway backend...');
    addLog('> ⏳ Please wait...', 'info');
    socket.emit('start-server');
    addUsage();
}

function stopServer() {
    if (!socket.connected) {
        addLog('> ❌ Not connected to backend!', 'error');
        return;
    }
    
    addLog('> 📡 Sending stop command to backend...');
    socket.emit('stop-server');
    addUsage();
}

function addUsage() {
    if (usageCount < UNLOCK_THRESHOLD) {
        usageCount++;
        localStorage.setItem('mineHostUsage', usageCount);
        updateUI();
    }
}

function updateUI() {
    const progress = Math.min((usageCount / UNLOCK_THRESHOLD) * 100, 100);
    document.getElementById('progress-fill').style.width = `${progress}%`;
    
    const statusText = document.getElementById('access-status');
    const xpText = document.getElementById('xp-text');

    if (usageCount >= UNLOCK_THRESHOLD) {
        statusText.innerHTML = "UNLOCKED 🔓";
        statusText.style.color = "#4caf50";
        xpText.innerHTML = "🎉 Browser access unlocked! You're a real one fr fr 💯";
    } else {
        const remaining = UNLOCK_THRESHOLD - usageCount;
        xpText.innerHTML = `🔥 ${remaining} more action${remaining > 1 ? 's' : ''} to unlock full browser access!`;
    }
}

function downloadConfig() {
    const content = `# MineHost Server Configuration
# Generated by MineHost Panel
# Made by Zenerity Studios

# Server Settings
server-port=25565
server-ip=
enable-query=true
query.port=25565

# Gameplay
gamemode=survival
difficulty=normal
hardcore=false
max-players=20
pvp=true
allow-flight=false
spawn-monsters=true
spawn-animals=true
spawn-npcs=true

# World
level-name=world
level-seed=
level-type=default
generate-structures=true
view-distance=10
simulation-distance=10

# Performance
max-tick-time=60000
network-compression-threshold=256

# MOTD
motd=§6Welcome to §bMineHost §7| §aZenerity Studios
server-name=MineHost Server

# Advanced
online-mode=true
white-list=false
enable-command-block=false
spawn-protection=16
resource-pack=
resource-pack-sha1=

# Logging
enable-status=true
enable-rcon=false`;
    
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    
    const a = document.createElement('a');
    a.href = url;
    a.download = 'server.properties';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    
    addLog('> 📥 Configuration file downloaded!', 'success');
    addLog('> ✅ Place this in your server directory', 'info');
    addUsage();
}

// Easter egg lol
let clickCount = 0;
document.querySelector('.logo').addEventListener('click', () => {
    clickCount++;
    if (clickCount === 5) {
        addLog('> 🎮 Konami code activated! Just kidding lmao', 'success');
        clickCount = 0;
    }
});